# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-feed

# Setup
title:            Kitaran Sea Campaign
tagline:          'A Psionics campaign for D&D 3e'
description:      'A Psionics campaign for D&D 3e'
url:              https://www.frimicc.com/kitaransea
baseurl:          /

author:
  name:           'Michael Friedman'
  url:            https://www.frimicc.com/
  email:          'michael@frimicc.com'
  twitter:        frimicc

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/frimicc/kitaransea
